name: Deploy to Github pages

on: 
  push: 
    branches: [master]

jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      -uses: action/checkout@v3
      -name: copy files to docs
      run: |
          mkdir docs
          cp index.html styles.css ./frontend/docs
      -name: Deploy with GitHub pages
      -uses: action/deploy-pages@v1
      with:  github-token: ${{ secrets.GITHUB_TOKEN }}
      publish-dir: ./frontend/docs 

      
        
